baseURL = "https://elisejohnson.co.uk"
languageCode = "en-gb"
title = "Elise Johnson | Acupuncture"
theme = "hargo"
summaryLength = "20"
paginate = 10
disqusShortname = ""

[params.plugins]
  # CSS Plugins
  [[params.plugins.css]]
  link = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  link = "plugins/slick/slick.css"
  [[params.plugins.css]]
  link = "plugins/themify-icons/themify-icons.css"

  # JS Plugins
  [[params.plugins.js]]
  link = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  link = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  link = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  link = "plugins/google-map/gmap.js"


############################## Navigation ###############################
[menu]
  [[menu.main]]
  name = "About Elise"
  URL = "about-elise"
  weight = 1
  [[menu.main]]
  name = "Qi Gong classes"
  URL = "qi-gong"
  weight = 2
  [[menu.main]]
  name = "In-person treatments"
  URL = "acupuncture-shiatsu-sessions"
  weight = 3
  [[menu.main]]
  name = "Chinese medicine by Zoom"
  URL = "chinese-medicine"
  weight = 4
  [[menu.main]]
  name = "Shiatsu baby course"
  URL = "shiatsu-baby-course"
  weight = 5
  [[menu.main]]
  name = "Contact"
  URL = "contact"
  highlight = "true"
  weight = 6

#################### default parameters ################################
[params]
logo = "images/Elise-Johnson-Logo2-Final.png"
footerImage = "images/Members_logo-1.gif"
home = "Home"
# Meta data
description = "Descripton"
author = "Elise Johnson"
# google map
gmapAPI = "https://maps.googleapis.com/maps/api/js?key=AIzaSyB6vJiBtIFjrz_cmMe1dwmNwaGUiKytSWc"
mapLatitude = "51.9076161195175"
mapLongitude = "0.8995877068542768"
mapMarker = "images/marker.png"
# Google Analitycs
googleAnalitycsID = "" # Your ID
# Contact Information
mobile = "07801254138"
email = "elise@elisejohnson.co.uk"
location = "155 Turner Road, Colchester, CO4 5XW"
copyright = "Copyright &copy; 2019-{year}. All Rights Reserved"

# Preloader
[params.preloader]
enable = false
preloader = "" # use .png , .svg or .gif format

